<a href="https://colab.research.google.com/github/MohdAffan27/AI-Learning-Journey/blob/main/PROJECTS/01_Student_Performance_EDA/Student_Performance_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

In [24]:
df = pd.read_excel("Student_Performance_Raw_Dataset.xlsx")

In [25]:
df.head()

,student_id,gender,age,study_hours,attendance,parental_education,internet_access,sleep_hours,previous_score,final_score
0,1085,Male,20.0,3.6,89.9,Bachelor's,No,6.1,84,78.1
1,1087,Female,23.0,7.5,96.9,PhD,Yes,6.3,75.9,73.8
2,1098,Female,19.0,7.6,72.5,Bachelor's,No,6.9,89.3,78.7
3,1116,Female,17.0,4.6,57.6,Diploma,Yes,7.1,64,60.1
4,1030,Female,19.0,4.7,76.3,NaN,Yes,8.4,64.9,67.4

In [26]:
df.shape

(153, 10)

In [27]:
df.columns

Index(['student_id', 'gender', 'age', 'study_hours', 'attendance',
       'parental_education', 'internet_access', 'sleep_hours',
       'previous_score', 'final_score'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          153 non-null    int64
 1   gender              153 non-null    object
 2   age                 152 non-null    float64
 3   study_hours         152 non-null    float64
 4   attendance          152 non-null    float64
 5   parental_education  152 non-null    object
 6   internet_access     153 non-null    object
 7   sleep_hours         152 non-null    float64
 8   previous_score      153 non-null    object
 9   final_score         152 non-null    float64
dtypes: float64(5), int64(1), object(4)
memory usage: 12.1+ KB

In [29]:
df.describe()

,student_id,age,study_hours,attendance,sleep_hours,final_score
count,153.00000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,1075.00000,20.789474,4.526316,77.165789,6.837500,59.847368
std,43.50862,10.751024,2.107091,13.942750,1.941591,11.610357
min,1001.00000,17.000000,-2.000000,55.500000,4.600000,33.300000
25%,1038.00000,18.000000,2.700000,62.950000,5.600000,52.800000
50%,1075.00000,20.000000,4.800000,77.150000,6.800000,59.850000
75%,1112.00000,22.000000,6.125000,89.025000,7.825000,66.225000
max,1150.00000,150.000000,7.900000,110.000000,25.000000,120.000000

check for empty cells

In [30]:
df.isna().sum()

student_id            0
gender                0
age                   1
study_hours           1
attendance            1
parental_education    1
internet_access       0
sleep_hours           1
previous_score        0
final_score           1
dtype: int64

Boolean operations for extraordinary values

In [31]:
(df['age'] < 0).sum()

np.int64(0)

In [32]:
(df['age'] < 0).sum()

np.int64(0)

In [33]:
df[df['age'] > 70]

,student_id,gender,age,study_hours,attendance,parental_education,internet_access,sleep_hours,previous_score,final_score
7,1082,Female,150.0,7.6,99.6,Diploma,No,8.2,77,82.7

In [34]:
df[df['attendance'] < 0]

Empty DataFrame
Columns: [student_id, gender, age, study_hours, attendance, parental_education, internet_access, sleep_hours, previous_score, final_score]
Index: []

In [35]:
(df['attendance'] > 100).sum()

np.int64(1)

In [36]:
df[df['attendance'] > 100]

,student_id,gender,age,study_hours,attendance,parental_education,internet_access,sleep_hours,previous_score,final_score
141,1100,Male,22.0,5.0,110.0,PhD,No,7.3,44.7,49.3

In [37]:
(df['study_hours'] < 0).sum()

np.int64(1)

In [38]:
df[df['study_hours'] < 0]

,student_id,gender,age,study_hours,attendance,parental_education,internet_access,sleep_hours,previous_score,final_score
47,1091,Female,17.0,-2.0,89.0,Bachelor's,Yes,6.6,79.7,72.6

In [39]:
(df['final_score'] < 0).sum()

np.int64(0)

In [40]:
(df['final_score'] > 100).sum()

np.int64(1)

Duplicate values count

In [41]:
df.duplicated().sum()

np.int64(3)

---
# Steps to clean Data


---

### Step 1 — Create a working copy

In [42]:
df_clean = df.copy()

### Step 2 — Remove exact duplicate rows
Now use Pandas' drop_duplicates() method on your working copy.

In [43]:
df_clean = df_clean.drop_duplicates()

### Step 3 — Verify your results
Now check the number of rows before and after cleaning, and confirm that no exact duplicates remain.

In [45]:
print("Original dataset shape:", df.shape)
print("Cleaned dataset shape:", df_clean.shape)

print("Remaining duplicate rows in copied dataset:", df_clean.duplicated().sum())

Original dataset shape: (153, 10)
Cleaned dataset shape: (150, 10)
Remaining duplicate rows in copied dataset: 0

### Step 4 — Investigate missing values

#### 4.1 Count missing values after duplicate removal
First, we need to check the missing values again because we've removed three rows. We shouldn't assume the counts are still the same.

In [46]:
df_clean.isnull().sum()

student_id            0
gender                0
age                   1
study_hours           1
attendance            1
parental_education    1
internet_access       0
sleep_hours           1
previous_score        0
final_score           1
dtype: int64

In [47]:
df_clean.isnull().sum().sum()

np.int64(6)

In [48]:
missing_percentage = (
    df_clean.isnull().sum().sum()
    / df_clean.size
) * 100

print(f"Missing data percentage: {missing_percentage:.2f}%")

Missing data percentage: 0.40%